In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('1.csv')

In [5]:

df.head()

,Unnamed: 0,Unnamed: 0.1,PRN,Epoch_Time_of_Clock,SV_Clock_Bias,SV_Clock_Drift,SV_Clock_Drift_Rate,IODE,Crs,Del_n,...,I_dot,Codes,GPS_week,L2_P_Data_flag,SV_accuracy,SV_health,Tgd,IODC,T_Tx,Fit_Interval
0,0,80,1,2017-11-01 14:00:00,-0.000008,-2.387424e-12,0,30,20.71875,4.874846e-09,...,2.239379e-10,1,1973,0,0,0,5.587935e-09,30,302466,0
1,1,88,1,2017-11-01 16:00:00,-0.000008,-2.387424e-12,0,31,16.81250,4.916991e-09,...,3.046555e-10,1,1973,0,0,0,5.587935e-09,31,309606,0
2,2,101,1,2017-11-01 18:00:00,-0.000008,-2.387424e-12,0,32,13.84375,4.874846e-09,...,2.971552e-10,1,1973,0,0,0,5.587935e-09,32,316806,0
3,3,109,1,2017-11-01 20:00:00,-0.000008,-2.387424e-12,0,33,12.28125,4.875203e-09,...,2.582250e-10,1,1973,0,0,0,5.587935e-09,33,324006,0
4,4,124,1,2017-11-01 22:00:00,-0.000008,-2.387424e-12,0,34,23.03125,4.753055e-09,...,2.000083e-10,1,1973,0,0,0,5.587935e-09,34,331206,0

In [38]:
#sqr_A = np.square(df.iloc[:,14:15])
#np.power(sqr_A, 2)


#for i in range(0,177):
GM = 3.986005 * 10**(14)
e = 7.292115*10**(-5)
pi = 3.1415926535898
crs = []
e = []
io = []
Omega = []
omega = []
M0 = []
Del_n = []
Omega_dot = []
i_dot = []
cus = []
cuc = []
crc = []
cis = []
cic = []

In [35]:
for i in range(0,178):
    temp =

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177